name: graph
channels:
  - defaults
  - pytorch
  - nvidia
dependencies:
  - python=3.11
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - scipy
  - jupyterlab
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8  
  - pytest
  - pylint
  - yapf
  - isort
  - pip
  - pip:
    - transformers[torch]
    - pillow
